title: "Harry Potter Murder Mystery"
description: "Annual Hogwarts Alumni Gala - A Murder Mystery Game"
baseurl: "/harry-potter-murder-mystery"
url: "https://msiebert.github.io"

markdown: kramdown
highlighter: rouge
theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/